// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupConnections() {
  return window['go']['main']['App']['BackupConnections']();
}

export function ChangePermissions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangePermissions'](arg1, arg2, arg3);
}

export function ConnectSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectSSH'](arg1, arg2, arg3);
}

export function ConnectSSHWithPassphrase(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectSSHWithPassphrase'](arg1, arg2, arg3, arg4);
}

export function CreateConnection(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateConnection'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateDesktopShortcut() {
  return window['go']['main']['App']['CreateDesktopShortcut']();
}

export function CreateDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateDirectory'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeletePath(arg1, arg2) {
  return window['go']['main']['App']['DeletePath'](arg1, arg2);
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function DownloadFileToDialog(arg1, arg2) {
  return window['go']['main']['App']['DownloadFileToDialog'](arg1, arg2);
}

export function EditFile(arg1, arg2) {
  return window['go']['main']['App']['EditFile'](arg1, arg2);
}

export function GetAboutInfo() {
  return window['go']['main']['App']['GetAboutInfo']();
}

export function GetActiveSessions() {
  return window['go']['main']['App']['GetActiveSessions']();
}

export function GetConnection(arg1) {
  return window['go']['main']['App']['GetConnection'](arg1);
}

export function GetDecryptedPassword(arg1) {
  return window['go']['main']['App']['GetDecryptedPassword'](arg1);
}

export function ImportConnectionFromBackup(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ImportConnectionFromBackup'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListDirectory(arg1, arg2) {
  return window['go']['main']['App']['ListDirectory'](arg1, arg2);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2);
}

export function RenamePath(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestoreConnections() {
  return window['go']['main']['App']['RestoreConnections']();
}

export function SelectPrivateKeyFile() {
  return window['go']['main']['App']['SelectPrivateKeyFile']();
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function UpdateConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function UploadFileData(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFileData'](arg1, arg2, arg3);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2, arg3);
}
