// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';
import {models} from '../models';
import {sftp} from '../models';

export function BackupConnections():Promise<void>;

export function BuildMenu():Promise<menu.Menu>;

export function ChangePermissions(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ConnectSSH(arg1:number,arg2:number,arg3:number):Promise<string>;

export function ConnectSSHWithPassphrase(arg1:number,arg2:string,arg3:number,arg4:number):Promise<string>;

export function CreateConnection(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<number>;

export function CreateDesktopShortcut():Promise<void>;

export function CreateDirectory(arg1:string,arg2:string):Promise<void>;

export function DeleteConnection(arg1:number):Promise<void>;

export function DeletePath(arg1:string,arg2:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadFileToDialog(arg1:string,arg2:string):Promise<void>;

export function EditFile(arg1:string,arg2:string):Promise<void>;

export function GetAboutInfo():Promise<Record<string, string>>;

export function GetActiveSessions():Promise<number>;

export function GetConnection(arg1:number):Promise<models.Connection>;

export function GetDecryptedPassword(arg1:number):Promise<string>;

export function ListConnections():Promise<Array<models.Connection>>;

export function ListDirectory(arg1:string,arg2:string):Promise<Array<sftp.FileInfo>>;

export function RenamePath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SelectPrivateKeyFile():Promise<string>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function UpdateConnection(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadFileData(arg1:string,arg2:string,arg3:string):Promise<void>;
